codecov:
  branch: platform

coverage:
  range: 60..100
  round: down
  precision: 5
  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        threshold: 50%

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
