- name: Install Go
  become: true
  apt:
    name:
      # Avalanche (in May 2020) requires Go 1.13. On Ubuntu 20.04 LTS this package,
      # provides the appropriate version.
      - golang-go
  tags:
    - golang_base
