- name: Install Avalanche dependencies
  become: true
  apt:
    name:
      # Build
      - cmake
      - curl
      - g++
      - libssl-dev
      - libuv1-dev
      - make
      # Staking key management
      - openssl
      - python3-cryptography
    state: present
