name: Ansible Lint
on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Ansible playbooks
        # Lastest commit, as of 30 Apr 2020
        uses: ansible/ansible-lint-action@6c8c141
        with:
          targets: |
            scripts/ansible/kill_playbook.yml
            scripts/ansible/ping_playbook.yml
            scripts/ansible/restart_playbook.yml
            scripts/ansible/service_playbook.yml
            scripts/ansible/update_playbook.yml

          args:
            -c scripts/ansible/.ansible-lint
